/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface InitialProxyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "check"
      | "checkcheck"
      | "factoryCreatePair"
      | "factorySetValidator"
      | "getNum"
      | "initialPlay"
      | "initialPlayPayable"
      | "poolMint"
      | "swapBNCForExactTokens"
      | "swapExactBNCForTokens"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "check", values: [BytesLike[]]): string;
  encodeFunctionData(
    functionFragment: "checkcheck",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "factoryCreatePair",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "factorySetValidator",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getNum", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialPlay",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "initialPlayPayable",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "poolMint",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapBNCForExactTokens",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      AddressLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactBNCForTokens",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      AddressLike,
      AddressLike
    ]
  ): string;

  decodeFunctionResult(functionFragment: "check", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "checkcheck", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "factoryCreatePair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "factorySetValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getNum", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initialPlay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialPlayPayable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "poolMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapBNCForExactTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactBNCForTokens",
    data: BytesLike
  ): Result;
}

export interface InitialProxy extends BaseContract {
  connect(runner?: ContractRunner | null): InitialProxy;
  waitForDeployment(): Promise<this>;

  interface: InitialProxyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  check: TypedContractMethod<[data: BytesLike[]], [boolean], "nonpayable">;

  checkcheck: TypedContractMethod<[num: BigNumberish], [boolean], "nonpayable">;

  factoryCreatePair: TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike],
    [boolean],
    "nonpayable"
  >;

  factorySetValidator: TypedContractMethod<
    [userAddress: AddressLike, tokenA: AddressLike, tokenB: AddressLike],
    [boolean],
    "nonpayable"
  >;

  getNum: TypedContractMethod<[], [bigint], "view">;

  initialPlay: TypedContractMethod<
    [data: BytesLike[]],
    [boolean],
    "nonpayable"
  >;

  initialPlayPayable: TypedContractMethod<
    [data: BytesLike[]],
    [boolean],
    "payable"
  >;

  poolMint: TypedContractMethod<
    [userAddress: AddressLike, tokenA: AddressLike, tokenB: AddressLike],
    [boolean],
    "nonpayable"
  >;

  swapBNCForExactTokens: TypedContractMethod<
    [
      pairAddress: AddressLike,
      outputAmount: BigNumberish,
      maxToken: BigNumberish,
      inputToken: AddressLike,
      outputToken: AddressLike,
      userAddress: AddressLike
    ],
    [boolean],
    "payable"
  >;

  swapExactBNCForTokens: TypedContractMethod<
    [
      pairAddress: AddressLike,
      inputAmount: BigNumberish,
      minToken: BigNumberish,
      inputToken: AddressLike,
      outputToken: AddressLike,
      userAddress: AddressLike
    ],
    [boolean],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "check"
  ): TypedContractMethod<[data: BytesLike[]], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "checkcheck"
  ): TypedContractMethod<[num: BigNumberish], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "factoryCreatePair"
  ): TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "factorySetValidator"
  ): TypedContractMethod<
    [userAddress: AddressLike, tokenA: AddressLike, tokenB: AddressLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getNum"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialPlay"
  ): TypedContractMethod<[data: BytesLike[]], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "initialPlayPayable"
  ): TypedContractMethod<[data: BytesLike[]], [boolean], "payable">;
  getFunction(
    nameOrSignature: "poolMint"
  ): TypedContractMethod<
    [userAddress: AddressLike, tokenA: AddressLike, tokenB: AddressLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapBNCForExactTokens"
  ): TypedContractMethod<
    [
      pairAddress: AddressLike,
      outputAmount: BigNumberish,
      maxToken: BigNumberish,
      inputToken: AddressLike,
      outputToken: AddressLike,
      userAddress: AddressLike
    ],
    [boolean],
    "payable"
  >;
  getFunction(
    nameOrSignature: "swapExactBNCForTokens"
  ): TypedContractMethod<
    [
      pairAddress: AddressLike,
      inputAmount: BigNumberish,
      minToken: BigNumberish,
      inputToken: AddressLike,
      outputToken: AddressLike,
      userAddress: AddressLike
    ],
    [boolean],
    "payable"
  >;

  filters: {};
}
