/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface WrappingInterface extends Interface {
  getFunction(
    nameOrSignature: "depositWBNC" | "owner" | "wbncContract" | "withdrawWBNC"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "depositWBNC",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "wbncContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawWBNC",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "depositWBNC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "wbncContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawWBNC",
    data: BytesLike
  ): Result;
}

export interface Wrapping extends BaseContract {
  connect(runner?: ContractRunner | null): Wrapping;
  waitForDeployment(): Promise<this>;

  interface: WrappingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  depositWBNC: TypedContractMethod<
    [userAddress: AddressLike],
    [boolean],
    "payable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  wbncContract: TypedContractMethod<[], [string], "view">;

  withdrawWBNC: TypedContractMethod<
    [userAddress: AddressLike, wbncAmount: BigNumberish],
    [boolean],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "depositWBNC"
  ): TypedContractMethod<[userAddress: AddressLike], [boolean], "payable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "wbncContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawWBNC"
  ): TypedContractMethod<
    [userAddress: AddressLike, wbncAmount: BigNumberish],
    [boolean],
    "payable"
  >;

  filters: {};
}
